constants: #커스텀 속성
  jwt:
    issuer: green502@green.com #jwt 토근 발행자 정보
    bearer-format: JWT

    claim-key: signedUser
    secret-key: DaeguGreenArtAcademyClass502MsaClassFighting #비밀 레시피 (절대 공개되어서는 안됨)

    access-token-cookie-name: access-token
    access-token-cookie-path: /
    access-token-cookie-validity-seconds: 900 #15분
    access-token-validity-milliseconds: 900_000 #15분

    refresh-token-cookie-name: refresh-token
    refresh-token-cookie-path: /api/user/reissue
    refresh-token-cookie-validity-seconds: 1_296_000 #15일
    refresh-token-validity-milliseconds: 1_296_000_000 #15일


spring:
  application:
    name:  board-auth
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/board_auth
    username: root
    password: green502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
